# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/project/calculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/project/calculator/build1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/project/calculator/build1/CMakeFiles /home/ubuntu/project/calculator/build1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/project/calculator/build1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calculatorscxml

# Build rule for target.
calculatorscxml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculatorscxml
.PHONY : calculatorscxml

# fast build rule for target.
calculatorscxml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/build
.PHONY : calculatorscxml/fast

#=============================================================================
# Target rules for targets named calculator_test

# Build rule for target.
calculator_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculator_test
.PHONY : calculator_test

# fast build rule for target.
calculator_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/build
.PHONY : calculator_test/fast

#=============================================================================
# Target rules for targets named calculatorscxml_autogen

# Build rule for target.
calculatorscxml_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculatorscxml_autogen
.PHONY : calculatorscxml_autogen

# fast build rule for target.
calculatorscxml_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml_autogen.dir/build.make CMakeFiles/calculatorscxml_autogen.dir/build
.PHONY : calculatorscxml_autogen/fast

#=============================================================================
# Target rules for targets named calculator_test_autogen

# Build rule for target.
calculator_test_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculator_test_autogen
.PHONY : calculator_test_autogen

# fast build rule for target.
calculator_test_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test_autogen.dir/build.make CMakeFiles/calculator_test_autogen.dir/build
.PHONY : calculator_test_autogen/fast

calculator.o: calculator.cpp.o
.PHONY : calculator.o

# target to build an object file
calculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculator.cpp.o
.PHONY : calculator.cpp.o

calculator.i: calculator.cpp.i
.PHONY : calculator.i

# target to preprocess a source file
calculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculator.cpp.i
.PHONY : calculator.cpp.i

calculator.s: calculator.cpp.s
.PHONY : calculator.s

# target to generate assembly for a file
calculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculator.cpp.s
.PHONY : calculator.cpp.s

calculator_logic.o: calculator_logic.cpp.o
.PHONY : calculator_logic.o

# target to build an object file
calculator_logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculator_logic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_logic.cpp.o
.PHONY : calculator_logic.cpp.o

calculator_logic.i: calculator_logic.cpp.i
.PHONY : calculator_logic.i

# target to preprocess a source file
calculator_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculator_logic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_logic.cpp.i
.PHONY : calculator_logic.cpp.i

calculator_logic.s: calculator_logic.cpp.s
.PHONY : calculator_logic.s

# target to generate assembly for a file
calculator_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculator_logic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_logic.cpp.s
.PHONY : calculator_logic.cpp.s

calculator_test.o: calculator_test.cpp.o
.PHONY : calculator_test.o

# target to build an object file
calculator_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_test.cpp.o
.PHONY : calculator_test.cpp.o

calculator_test.i: calculator_test.cpp.i
.PHONY : calculator_test.i

# target to preprocess a source file
calculator_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_test.cpp.i
.PHONY : calculator_test.cpp.i

calculator_test.s: calculator_test.cpp.s
.PHONY : calculator_test.s

# target to generate assembly for a file
calculator_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_test.cpp.s
.PHONY : calculator_test.cpp.s

calculator_test_autogen/mocs_compilation.o: calculator_test_autogen/mocs_compilation.cpp.o
.PHONY : calculator_test_autogen/mocs_compilation.o

# target to build an object file
calculator_test_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_test_autogen/mocs_compilation.cpp.o
.PHONY : calculator_test_autogen/mocs_compilation.cpp.o

calculator_test_autogen/mocs_compilation.i: calculator_test_autogen/mocs_compilation.cpp.i
.PHONY : calculator_test_autogen/mocs_compilation.i

# target to preprocess a source file
calculator_test_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_test_autogen/mocs_compilation.cpp.i
.PHONY : calculator_test_autogen/mocs_compilation.cpp.i

calculator_test_autogen/mocs_compilation.s: calculator_test_autogen/mocs_compilation.cpp.s
.PHONY : calculator_test_autogen/mocs_compilation.s

# target to generate assembly for a file
calculator_test_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculator_test.dir/build.make CMakeFiles/calculator_test.dir/calculator_test_autogen/mocs_compilation.cpp.s
.PHONY : calculator_test_autogen/mocs_compilation.cpp.s

calculatorscxml_autogen/mocs_compilation.o: calculatorscxml_autogen/mocs_compilation.cpp.o
.PHONY : calculatorscxml_autogen/mocs_compilation.o

# target to build an object file
calculatorscxml_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculatorscxml_autogen/mocs_compilation.cpp.o
.PHONY : calculatorscxml_autogen/mocs_compilation.cpp.o

calculatorscxml_autogen/mocs_compilation.i: calculatorscxml_autogen/mocs_compilation.cpp.i
.PHONY : calculatorscxml_autogen/mocs_compilation.i

# target to preprocess a source file
calculatorscxml_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculatorscxml_autogen/mocs_compilation.cpp.i
.PHONY : calculatorscxml_autogen/mocs_compilation.cpp.i

calculatorscxml_autogen/mocs_compilation.s: calculatorscxml_autogen/mocs_compilation.cpp.s
.PHONY : calculatorscxml_autogen/mocs_compilation.s

# target to generate assembly for a file
calculatorscxml_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/calculatorscxml_autogen/mocs_compilation.cpp.s
.PHONY : calculatorscxml_autogen/mocs_compilation.cpp.s

qrc_qmake_qml_resources.o: qrc_qmake_qml_resources.cpp.o
.PHONY : qrc_qmake_qml_resources.o

# target to build an object file
qrc_qmake_qml_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/qrc_qmake_qml_resources.cpp.o
.PHONY : qrc_qmake_qml_resources.cpp.o

qrc_qmake_qml_resources.i: qrc_qmake_qml_resources.cpp.i
.PHONY : qrc_qmake_qml_resources.i

# target to preprocess a source file
qrc_qmake_qml_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/qrc_qmake_qml_resources.cpp.i
.PHONY : qrc_qmake_qml_resources.cpp.i

qrc_qmake_qml_resources.s: qrc_qmake_qml_resources.cpp.s
.PHONY : qrc_qmake_qml_resources.s

# target to generate assembly for a file
qrc_qmake_qml_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatorscxml.dir/build.make CMakeFiles/calculatorscxml.dir/qrc_qmake_qml_resources.cpp.s
.PHONY : qrc_qmake_qml_resources.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... calculator_test_autogen"
	@echo "... calculatorscxml_autogen"
	@echo "... calculator_test"
	@echo "... calculatorscxml"
	@echo "... calculator.o"
	@echo "... calculator.i"
	@echo "... calculator.s"
	@echo "... calculator_logic.o"
	@echo "... calculator_logic.i"
	@echo "... calculator_logic.s"
	@echo "... calculator_test.o"
	@echo "... calculator_test.i"
	@echo "... calculator_test.s"
	@echo "... calculator_test_autogen/mocs_compilation.o"
	@echo "... calculator_test_autogen/mocs_compilation.i"
	@echo "... calculator_test_autogen/mocs_compilation.s"
	@echo "... calculatorscxml_autogen/mocs_compilation.o"
	@echo "... calculatorscxml_autogen/mocs_compilation.i"
	@echo "... calculatorscxml_autogen/mocs_compilation.s"
	@echo "... qrc_qmake_qml_resources.o"
	@echo "... qrc_qmake_qml_resources.i"
	@echo "... qrc_qmake_qml_resources.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

